### PR TITLE
Update certificate

### LINKED ISSUE #13: "Timed out connecting to Loki"
I followed this tutorial [https://grafana.com/blog/2021/07/19/iot-at-your-home-work-or-data-center-with-prometheus-metrics-and-grafana-cloud/](url) to get the ESP32 running. After I fixed the problem with the wrong certificate #10  the ESP was finnaly able to connect successfully but is getting always a timeout:

`1675064609430`
`Begin serialization: Free Heap: 240572`
`Bytes used for serialization: 148`
`After serialization: Free Heap: 240572`
`After Compression Init: Free Heap: 240044`
`Required buffer size for compression: 204`
`Compressed Len: 132`
`After Compression: Free Heap: 240572`
`Sending To Prometheus`
`Connecting...`
`Connected.`
`Sent, waiting for response`
`Timed out connecting to Loki`
`1675064628071`

I kicked out everything out related to the sensors and just tried to write the system time to the Grafan cloud. Things that I already tried:

- Generate different API tokens with different roles (admin, metricsPublisher,...)
- Change the timeout values in the library.
- 3 different WiFi networks did not change anything. 
- Tried Loki and Prometheus logins/API keys

Any suggestion or deeper debugging information would be higly apreciated. I don' t get the point what is going wrong.

### PR DESCRIPTION
**Pull request by fridgepoet**
Apparently digicert changed a root certificate which altered Grafana's certificate.
This PR replaces the certificate with an updated one. I removed the comment about USERTrust since it is digicert, but let me know if I misunderstood and should put it back.

Fixes https://github.com/grafana/prometheus-arduino/issues/13

### CODE REVIEW

**Review by ivanahuckova — APPROVED** [review]
🫶

**Comment by ivanahuckova** [comment]
if you have a time, would you do the same in https://github.com/grafana/loki-arduino as well.

**Comment by fridgepoet** [comment]
@slim-bean would you be able to help out on the failing build? 

I think I can merge this change anyway, what do you both think?

**Comment by fridgepoet** [comment]
going to merge this for now and try to follow up separately on the CI failure

**Pull request merged**
